In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import mean_squared_error,mean_absolute_error
#plt.rcParams["font.family"] = 'Arial Unicode MS'
#plt.rcParams['axes.unicode_minus'] = False

In [7]:
traing=pd.read_excel('样本数据.xlsx',index_col=0)
traing.head()
data=pd.read_excel('优化之后各个样本数据.xlsx',index_col=0).reset_index(drop=True)
data.head()

,0,1,2,3,4,5,6,7,8
0,40.000000,150.0,250.000000,0.6,2.770312,3485.518691,12.326774,90.6,3.2
1,54.709687,150.0,253.278114,0.6,2.550000,3468.291468,2.231152,90.5,3.2
2,43.204892,150.0,250.000000,0.6,3.354981,3496.771184,0.000000,90.7,3.2
3,40.000000,150.0,250.000000,0.6,2.550000,3485.033491,0.000000,90.4,3.2
4,40.000000,150.0,250.000000,0.6,2.550000,3472.659257,54.360831,89.6,3.2

In [12]:
data.columns=traing.columns

In [14]:
#读取因变量
y=pd.read_excel('/Users/zhongrunping/Desktop/jupyter文件夹/数学建模/RON损失(不是变量).xlsx')[::-1].reset_index(drop=True)
y=y.iloc[:,2]

In [15]:
#训练模型
svr=SVR(kernel='poly',coef0=5,degree=3,cache_size=800).fit(traing,y)
mean_absolute_error(y,svr.predict(traing))
#训练平均的绝对误差0.15

0.15308364807468453

In [17]:
#预测优化后的
y_after=svr.predict(data)

In [19]:
(y-y_after).mean()
#平均降低了损失值0.69

0.693643066115094

In [21]:
#平均损失降幅55%
((y-y_after).mean())/y.mean()

0.5528052881005532

In [26]:
loss=pd.DataFrame(y_after,columns=['损失值'])

In [44]:
#将损失值从小到大排序
loss.sort_values(by='损失值')

          损失值
17   0.551785
133  0.551798
152  0.551842
9    0.551871
277  0.551896
..        ...
144  0.609783
32   0.626764
155  0.725893
98   0.753653
228  0.794241

[325 rows x 1 columns]

In [45]:
sorted_loss=data.iloc[loss.sort_values(by='损失值').index,:]

In [51]:
sorted_loss=sorted_loss.reset_index()

In [54]:
sorted_loss['index']=sorted_loss['index']+1

In [57]:
sorted_loss.columns

,index,原料换热器管程总管进口温度,1.0MPa蒸汽进装置温度,氮气进装置流量,稳定塔顶压力,K101机出口压力,蒸汽进装置流量,加氢裂化轻石脑油进装置流量,辛烷值1RON,"硫含量2,μg/g"
0,18,40.00000,150.000000,250.0,0.625853,2.550000,3499.169906,0.000000,88.0,3.2
1,134,40.00000,150.000000,250.0,0.600000,3.193009,3499.437051,0.000000,89.2,3.2
2,153,40.00000,150.000000,250.0,0.600000,2.550000,3498.676599,0.000000,87.5,3.2
3,10,40.00000,150.000000,250.0,0.600000,2.550000,3499.253620,0.000000,90.2,3.2
4,278,40.00000,150.000000,250.0,0.628377,3.213721,3499.274449,0.000000,89.5,4.4
...,...,...,...,...,...,...,...,...,...,...
320,145,40.00000,150.117689,250.0,0.622994,3.217539,3473.566447,681.419745,88.7,3.5
321,33,55.24177,155.940657,250.0,0.646869,3.482445,3472.223481,853.526770,88.4,3.2
322,156,40.00000,150.000000,250.0,0.620790,2.550000,3474.512465,2482.142753,89.8,3.2
323,99,40.00000,160.662344,250.0,0.661049,2.550000,3463.008669,2922.740975,91.1,3.2
324,229,40.00000,150.000000,250.0,0.687414,2.907766,3440.221793,3761.294447,90.4,3.2

In [59]:
sorted_loss.columns=['样本编号', '原料换热器管程总管进口温度', '1.0MPa蒸汽进装置温度', '氮气进装置流量', '稳定塔顶压力',
       'K101机出口压力', '蒸汽进装置流量', '加氢裂化轻石脑油进装置流量', '辛烷值1RON', '硫含量2,μg/g']

In [60]:
sorted_loss

,样本编号,原料换热器管程总管进口温度,1.0MPa蒸汽进装置温度,氮气进装置流量,稳定塔顶压力,K101机出口压力,蒸汽进装置流量,加氢裂化轻石脑油进装置流量,辛烷值1RON,"硫含量2,μg/g"
0,18,40.00000,150.000000,250.0,0.625853,2.550000,3499.169906,0.000000,88.0,3.2
1,134,40.00000,150.000000,250.0,0.600000,3.193009,3499.437051,0.000000,89.2,3.2
2,153,40.00000,150.000000,250.0,0.600000,2.550000,3498.676599,0.000000,87.5,3.2
3,10,40.00000,150.000000,250.0,0.600000,2.550000,3499.253620,0.000000,90.2,3.2
4,278,40.00000,150.000000,250.0,0.628377,3.213721,3499.274449,0.000000,89.5,4.4
...,...,...,...,...,...,...,...,...,...,...
320,145,40.00000,150.117689,250.0,0.622994,3.217539,3473.566447,681.419745,88.7,3.5
321,33,55.24177,155.940657,250.0,0.646869,3.482445,3472.223481,853.526770,88.4,3.2
322,156,40.00000,150.000000,250.0,0.620790,2.550000,3474.512465,2482.142753,89.8,3.2
323,99,40.00000,160.662344,250.0,0.661049,2.550000,3463.008669,2922.740975,91.1,3.2
324,229,40.00000,150.000000,250.0,0.687414,2.907766,3440.221793,3761.294447,90.4,3.2

In [66]:
sorted_loss['损失值']=loss.sort_values(by='损失值').values

In [69]:
sorted_loss.to_excel('./优化数据分析/损失值排序.xlsx',index=None)

In [94]:
#pd.concat([data,y,loss],axis=1).to_excel('./优化数据分析/样本优化前后损失值.xlsx',index=None)

1.8200000000000074